package laundrycommon.view;

import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Spectore
 */
public abstract class Viewer2 extends javax.swing.JFrame {
    private TableRowSorter<TableModel> tableSorter; //TableRowSorter for sorting and filtering the table
    protected DefaultTableModel viewerDTM;         //TableModel of the table.
    protected JDialog addDialog;

    /**
     * Creates new form Viewer2
     */
    public Viewer2(String title) {
        initComponents();
        //
        //Initialize browser table
        //
        viewerDTM = (DefaultTableModel) new DefaultTableModel();           //Initialize field customerBrowserDTM
        viewerTable.setModel(viewerDTM);
        tableSorter = new TableRowSorter<TableModel>(viewerDTM);    //Create TableRowSorter using customerBrowserDTM as the underlying Model
        viewerTable.setRowSorter(tableSorter);
        
        //
        //Initialize other components.
        //
        setTitle(title);         //Set the title
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewerTableScrollPane = new javax.swing.JScrollPane();
        viewerTable = new javax.swing.JTable();
        toolBar = new javax.swing.JToolBar();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewerTable.setAutoCreateRowSorter(true);
        viewerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        viewerTable.setShowHorizontalLines(false);
        viewerTable.getTableHeader().setReorderingAllowed(false);
        viewerTableScrollPane.setViewportView(viewerTable);

        toolBar.setRollover(true);

        addButton.setText("Add");
        addButton.setFocusable(false);
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        toolBar.add(addButton);

        editButton.setText("Edit");
        editButton.setFocusable(false);
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(editButton);

        deleteButton.setText("Delete");
        deleteButton.setFocusable(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        toolBar.add(deleteButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewerTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewerTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        initAddDialog();
        addDialog.setVisible(true);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
    }//GEN-LAST:event_deleteButtonActionPerformed
    
    protected abstract void initAddDialog();
        
     /**
     * Populates the table with data taken from DB Called by extending browser
     * classes to populate the browser table with data relevant to that browser
     * This method first refreshes the modelList(ArrayList) with data taken from
     * the DB and then calls populateTableFromList()
     */
    protected abstract void populateTableFromDB();

    //
    // Populates the table with data taken from the dataList(ArrayList).
    //
    protected abstract void populateTableFromList();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JToolBar toolBar;
    protected javax.swing.JTable viewerTable;
    private javax.swing.JScrollPane viewerTableScrollPane;
    // End of variables declaration//GEN-END:variables
}
